### PR TITLE
Add SimdBlockFilter to the bulk benchmark.

### PR DESCRIPTION
**Pull request by jbapple-cloudera**
This also condenses the output format for that benchmark and throws an
exception if a SimdBlockFilter is constructed on a machine without
AVX2 instructions, on which Add() and Find() will fail.

### CODE REVIEW

**Comment by jbapple-cloudera** [comment]
@apc999 Any updates on this?

**Comment by jbapple-cloudera** [comment]
@dave-andersen Any news?

**Comment by jbapple-cloudera** [comment]
@binfan999 Any news on this?

**Comment by dave-andersen** [comment]
Sorry - I think Bin and I probably both thought the other was handling it.  Looking at. :)

**Pull request merged**
